# -*- mode: ruby -*-
# vi: set ft=ruby :
APP_NAME=File.basename(File.expand_path("..", Dir.pwd))
APP_HOME=File.join(File.dirname(__FILE__), '../')

Vagrant.configure("2") do |config|

  config.vm.provision "shell" do |s|
    s.path = "./prepare.sh"
  end

  config.vm.define "vm" do |vm|
    vm.vm.hostname = "#{APP_NAME}"
    vm.vm.box = "centos/7"
    vm.ssh.insert_key = false
    vm.vm.network "private_network", type: "dhcp"
    vm.vm.synced_folder APP_HOME, "/opt/#{APP_NAME}"

    vm.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.cpus = 1
      vb.memory = "512"
      vb.name = "#{APP_NAME}"
    end

  end

end